[문제1]  
리스트에 저장된 문자열 중에서 길이가 5인 것들만 리스트 형태로 출력하도록 구현하세요.  

a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']  


[출력결과]  
['alpha', 'bravo', 'delta', 'hotel', 'india']

In [ ]:
a = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']

b = [i for i in a if len(i) ==5]
b

['alpha', 'bravo', 'delta', 'hotel', 'india']

[문제2]    
가로 크기를 저장한 리스트를 활용해서 가로 크기가 불규칙한  리스트를 생성하도록 프로그램을 구현하세요.

a = [3, 1, 3, 2, 5]  


[출력결과]  
[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


In [ ]:
a = [3, 1, 3, 2, 5]
b = [[0] * i for i in a]
b

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

[문제3]    
포트폴리오의 총 비용을 계산하는 프로그램을 구현하세요.   

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]     

[출력결과]  
44671.15

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
cost = sum([ s['shares'] * s['price'] for s in portfolio ])
cost


[3220.0000000000005, 4555.0, 12516.0, 10246.0, 3835.1499999999996, 3254.9999999999995, 7044.0]


44671.15

[문제4]  
포트폴리오에서 100주 이상 보유한 종목의 리스트를 출력하는 프로그램을 구현하세요.    
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  


[출력결과]  
[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]


In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
more100 = [ s for s in portfolio if s['shares'] >= 100 ]
more100

[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]

[문제5]

보유한 MSFT와 IBM주식 전체 리스트를 출력하는 프로그램을 구현하세요.  

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  

[출력결과]   
[{'name': 'IBM', 'price': 91.1, 'shares': 50},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200},
 {'name': 'MSFT', 'price': 65.1, 'shares': 50},
 {'name': 'IBM', 'price': 70.44, 'shares': 100}]  



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
msftibm = [ s for s in portfolio if s['name'] in {'MSFT','IBM'} ]
msftibm

[{'name': 'IBM', 'shares': 50, 'price': 91.1},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'MSFT', 'shares': 50, 'price': 65.1},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]

[문제6]
보유 종목 중 가격이 10,000달러가 넘는 것의 리스트를 구현하는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]    
[{'name': 'CAT', 'price': 83.44, 'shares': 150},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200}]

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

cost10k = [ s for s in portfolio if s['shares'] * s['price'] > 10000 ]
cost10k

[{'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23}]

[문제7]   
portfolio에서 얻은 name과 shares를 가지고 튜플의 리스트 (name, shares)를 만드는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]   
[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
name_shares =[ (s['name'], s['shares']) for s in portfolio ]
name_shares

[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]

[문제8]  

리스트에서 int만 추출하는 프로그램을 구현하세요.  
oldlist = [1, 2, 'A', False, 3]

[출력결과]   
[1, 2, 3]  


In [ ]:
oldlist = [1, 2, 'A', False, 3]

newlist = [i for i in oldlist if type(i)==int]
newlist

[1, 2, 3]

[문제9]   
1부터 10까지의 홀수, 짝수로 출력하는 프로그램을 구현하세요.

[출력결과]   
{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}


In [ ]:
result = { n:'짝수' if n%2==0 else '홀수' for n in range(1, 11)}
result

{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}

In [ ]:
a = [1,2,3]
for i in a:
  if i%2==0:
    continue
  print(i)

1
3


[문제10]
if~else문을 이용해서 년도에 해당하는 띠를 구하는 프로그램을 구현하시오.
단, 년도은 input()으로 입력받음.

12가지 띠
원숭이, 닭, 개, 돼지, 쥐, 소, 호랑이, 토끼, 용, 뱀, 말, 양

띠구하는 공식
year%12의 결과가
0이면 "원숭이", 1이면 "닭" 2이면 "개", 3이면 "돼지",
4이면 "쥐", 5이면 "소", 6이면 "호랑이", 7이면 "토끼",
8이면 "용", 9이면 "뱀", 10이면 "말", 11이면 "양"

출력결과
2012년도의 태생은 용띠입니다.

In [1]:
# 연도 입력 받기
year = int(input("연도를 입력하세요: "))

# year % 12 값을 기반으로 띠 계산
remainder = year % 12

if remainder == 0:
    zodiac = "원숭이"
elif remainder == 1:
    zodiac = "닭"
elif remainder == 2:
    zodiac = "개"
elif remainder == 3:
    zodiac = "돼지"
elif remainder == 4:
    zodiac = "쥐"
elif remainder == 5:
    zodiac = "소"
elif remainder == 6:
    zodiac = "호랑이"
elif remainder == 7:
    zodiac = "토끼"
elif remainder == 8:
    zodiac = "용"
elif remainder == 9:
    zodiac = "뱀"
elif remainder == 10:
    zodiac = "말"
else:  # remainder == 11
    zodiac = "양"

# 결과 출력
print(f"{year}년도의 태생은 {zodiac}띠입니다.")


2012년도의 태생은 용띠입니다.


[문제11] list comprehension을 이용해서 1부터 10까지 합계 구하기

In [7]:
sum_total = sum([i for i in range(1, 11)])
print("1부터 10까지의 합계는", sum_total, "입니다.")


1부터 10까지의 합계는 55 입니다.


[문제12] A 학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과 같다.  
[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

for문을 사용하여 A 학급의 평균 점수를 구해 보자.

In [8]:
# 점수 리스트
scores = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

# 리스트 컴프리헨션을 사용해 총점 계산
total = sum([score for score in scores])

# 평균 계산
average = total / len(scores)

# 결과 출력
print("A 학급의 평균 점수는", average, "입니다.")


A 학급의 평균 점수는 79.0 입니다.


문제13) 
======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 1
메뉴명: 짜짜
가격: 3000
신규 메뉴 짜짜(이)가 등록되었습니다.
{'짜짜': '3000'}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 2

==========메뉴판==========
짜짜 : 3000원
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기
> 3

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 3
프로그램을 종료합니다.

In [ ]:
foods = {}

while True:
    print("\n======음식점 메뉴 관리 프로그램======")
    print("1. 신규 메뉴 등록")
    print("2. 메뉴판 전체 보기")
    print("3. 프로그램 종료")
    num = int(input("> "))

    if num == 1:
        # 1. 메뉴명을 입력받아 해당메뉴가 사전에 키로 존재한다면
        #    "이미 등록된 메뉴입니다"를 출력하세요
        # 2. 사전에 존재하지 않는 메뉴(key)라면 가격을 입력받아
        #    key:value쌍으로 맵핑하여 사전에 저장하세요.
        f_name = input("메뉴명: ")

        if f_name not in foods:
            price = input("가격: ")
            foods[f_name] = price
            print("신규 메뉴 %s(이)가 등록되었습니다." % f_name)
        else:
            print("이미 등록된 메뉴입니다.")

        print(foods)

    elif num == 2:
        # 1. 모든 키를 뽑아내서 리스트로 만드세요.
        # 2. 해당 리스트를 반복문으로 순회하여 메뉴와 가격을 출력하세요.
        #  ex) 출력 예시: "김치찌개 : 7000원"
        menulist = foods.keys()

        print("\n==========메뉴판==========")
        for m in menulist:
            print("%s : %s원" % (m, foods[m]))
        print("----------------------------------")
        print("1. 수정 | 2. 삭제 | 3. 나가기")
        select = int(input("> "))

        if select == 1:
            name = input("가격을 변경할 메뉴의 이름을 입력하세요: ")

            # 사전에 해당 메뉴가 존재하는지 확인
            if name in foods:
                newprice = input("변경할 가격 입력: ")
                # 해당 메뉴이름의 가격 데이터 newprice로 수정
                foods[name] = newprice
                print("%s의 가격이 %s원으로 변경되었습니다." % (name, newprice))
            else :
                print("%s(은)는 등록된 메뉴가 아닙니다." % name)
        elif select == 2:
            name = input("삭제할 메뉴의 이름을 입력하세요: ")

            # 사전에 해당 메뉴가 존재하는지 확인
            if name in foods:
                # 해당 메뉴 데이터 삭제
                del(foods[name])
                print("%s이(가) 삭제되었습니다." % name)
            else:
                print("%s(은)는 등록된 메뉴가 아닙니다." % name)
        elif select == 3:
            continue

    elif num == 3:
        print("프로그램을 종료합니다.")
        break
